name=JavaDoc
category=Utilities
authors=[Henning Kiel](https://github.com/hkiel)
url=https://github.com/hkiel/JavaDoc
sentence=Generate JavaDoc for sketch.
paragraph=
version=5
prettyVersion=1.0.4
lastUpdated=0
minRevision=0
maxRevision=0
